// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoh4lONbC0b0QddcSQxqFePRlsQ-Le2gE',
    appId: '1:798073935041:web:982e32273e5738aaf2b040',
    messagingSenderId: '798073935041',
    projectId: 'the-marshes-experience',
    authDomain: 'the-marshes-experience.firebaseapp.com',
    databaseURL: 'https://the-marshes-experience-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'the-marshes-experience.firebasestorage.app',
    measurementId: 'G-2QSSZWZDMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgTrsRdD7cLLAU0LQ_o6wcLSuXP_vQRo',
    appId: '1:798073935041:android:be6822fdffe404c2f2b040',
    messagingSenderId: '798073935041',
    projectId: 'the-marshes-experience',
    databaseURL: 'https://the-marshes-experience-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'the-marshes-experience.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw0GiNkBmv5du0kBroe__exxEucRaS9G8',
    appId: '1:798073935041:ios:67864521d09f3166f2b040',
    messagingSenderId: '798073935041',
    projectId: 'the-marshes-experience',
    databaseURL: 'https://the-marshes-experience-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'the-marshes-experience.firebasestorage.app',
    iosBundleId: 'com.example.theMarshesExperience',
  );
}
